### PR TITLE
[Bug 1206864] Localize known API error messages.

### PR DESCRIPTION
**Pull request by mythmon**
It's, well, not pretty. I think it works though. Almost makes me wish JS had macros.

I think this is all the errors we'll get. It is all that are mentioned in the bugs, and all that I could figure out how to trigger in places that called `refresh_error_list`. Though maybe there are some API error messages where `refresh_error_list` isn't called?

Did I miss anything? r?

### CODE REVIEW

**Comment by rehandalal** [comment]
I think there are a bunch of other error messages the API might return

**Comment by mythmon** [comment]
Any ideas how we can get a list of these? I guess I could go crawl through Sumo's code and find all the errors it might return. But that wouldn't include anything DRF can throw. Maybe we could lean on QA?

**Comment by rehandalal** [comment]
Here are the ones I had in my kitsune PR:
`Can't change this field.`
`Usernames may only be letters, numbers, "." and "-".`
`No matching user setting found.`
`Unable to generate username.`

**Comment by mythmon** [comment]
I don't think most of those will get shown to the user. "Usernames may only be letters..." probably will though. I'll add all of them just to be safe.

**Comment by mythmon** [comment]
Fixed the merge errors. Any thing else we can do here?

**Comment by rehandalal** [comment]
lgtm. let's ship it! i guess QA will tell us if we missed anything. r+

**Pull request merged**
