### PR TITLE
Added check so blank questions cannot be submitted

### PR DESCRIPTION
**Pull request by mrakestraw13**
I Added an "if" statement to the "submit_comment()" function in "question_controller.js".  Tested this using the firefoxOS emulator.

### CODE REVIEW

**Comment by mythmon** [comment]
Are you sure you tested this right? I don't see any way it could possible work, seeing how `NULL` doesn't exist, `=` is the assignment operator, not a comparison operator. In fact this likely causes all questions to have no content, regardless of if the user typed something in.

**Comment by mrakestraw13** [comment]
Oh, you are right.  Long story short I had to re-download the code and re-work the bug and must have not noticed I did that.  I will fix it and re-submit.  Other than my obvious oversight any suggestions or comments about my submission?  Thank you again for catching that.

**Comment by mythmon** [comment]
You should know that pushing new commits to a pull request doesn't notify anyone. You have to make a comment so someone will see it.

You only corrected half of my comments. `NULL` is not a valid value in javascript. The correct value is `null`, but that is also no the right thing to do here. Your lines should be this

```javascript
if (comment === '') {
  return;
}
```

**Comment by Rik** [comment]
I merged this in 2a597f7

**Pull request closed without merging**
